---
title: "README"
author: "Matthew Sheffer"
date: "February 9, 2017"
output: md_document
tables: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matthew Sheffer's Example Analytics Projects

-----

##Unfortunately, almost all the work I do is with data that is owned by someone else, or at the very least, the results cannot be shared in even a masked form.  

As a result, I've attempted to create some repos here that show the general types of research project I'm often called on to perform in my job even though the data or projects are not from my professional life at all.  Some of these datasets or project come from schools or educational institutions I've attended or else have been sufficiently masked and altered to be usable without having to worry about confidentiality.



##[Data Science Specialization Capstone Project](https://github.com/msheffer2/Data-Science-Specialization)

-----

The files in this repository were used as my Capstone submission for the Johns Hopkins Data Science Specialization. The courses in the specialization didn't offer a lot of new material in regards to modeling but it was great R practice, which I needed at that time.  I used the Yelp Dataset Challenge data to develop predictive models to find out what types of review text could predict good reviews (5-star) or poor review (1-star).  I don't use NLP in my current work but the overall work flow of the project is representative of how I like to approach problems.



##[Hiearchical Bayes Choice Study](https://github.com/msheffer2/Hierarchical-Bayes-Choice-Study)

-----

It's nearly impossible to find choice study data that isn't protected by client confidentiality, so I used this data from my Marketing Analytics course at Northwestern to show how I might go about implementing a discrete choice model to answer marketing questions about a new product offering.



##[Low Sample Cluster Prediction](https://github.com/msheffer2/Low-Sample-Cluster-Prediction)

-----

Clustering data and uncovering market segments is a lot of fun (at least to me).  Very often in my work, I also am required to develop a predictive algorithm to predict segment membership onto a target list of customers for a client.  In my work, though, we are often hampered by low sample sizes which makes it difficult to assess predictive accuracy well.  In this repo, I walk through an example of how I use cross-validation to solve this problem.



##[Bus Ridership Prediction](https://github.com/msheffer2/Bus-Ridership-Prediction)

-----

This repo contains the files I used to complete my Capstone for my MS in Predictive Analytics at Northwestern.  Unlike most capstone projects, this had real-world data and an actual client!  My task for the Capstone was to find a way to accurately predict bus ridership for a city in the Northwest US that was more robust, systematic, and accurate then their current method which was somewhat arbitrarily handled inside spreadsheets.


